defaults:
  - _self_
  - model: seldnet

wandb:
  entity: "nsfw-princeton-university"
  project: "co2_aemodes"
  mode: "offline"
  id: "add dropout"
train:
  data_file: data/co2_250_detector.pkl
  ckpt_file: mdl.pth
  output_dir: outputs/test
  epochs: 50
  batch_size: 64
  num_workers: 3
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
early_stopper:
  _target_: aemodes.utils.earlystopping.EarlyStopping
  patience: 3
  delta: 1e-4
criterion:
  _target_: aemodes.nn.loss.MSELoss
validation_loss:
  BCE: aemodes.nn.loss.BCELoss
  MSE: aemodes.nn.loss.MSELoss
  TPR: aemodes.nn.loss.TPRLoss
  FPR: aemodes.nn.loss.FPRLoss
  FOC: aemodes.nn.loss.FocalLoss
  MAE: aemodes.nn.loss.MAELoss